---
cap-location: margin
css:  'custom.css'
output:
  pagedown::html_paged: 
    toc: true
    self_contained: false
toc-title: 'IPUMS PMA Codebook: <br>Pregnancy Termination Variables'
lot: false
lof: false
paged-footnotes: true
---

```{r, echo=FALSE,results='hide', message=FALSE}
source(here::here("r/utilities.r"))
set_postpath("2022-12-09-data-dictionary")
library(ipumsr)
library(tidyverse)
library(gtsummary)
library(gt)

dat <- read_ipums_micro(
  ddi = "data/pma_00180.xml",
  data = "data/pma_00180.dat.gz"
)
```


```{r, echo = FALSE, results='asis'}
dd <- read_rds("data/dd.rds.gz") %>% 
  slice(-c(1:12)) %>% 
  mutate(
    var_name = var_name %>% 
      paste("#", ., "{.unnumbered}"),
    comp = comp %>% 
      str_replace("Comparability", "#### Comparability {.unnumbered}\n"),
    avail = avail %>% 
      str_replace_all("\n", "\n - ") %>% 
      str_replace("Availability", "#### Availability {.unnumbered}\n"),
    universe = universe %>% 
      str_replace_all("\n", "\n - ") %>% 
      str_replace("Universe", "#### Universe {.unnumbered}\n")
  )

dd %>% 
  ungroup() %>% 
  pwalk(function(...){
    text <- list(...)
    cat(text$var_name, "\n\n")
    cat(text$var_desc, "\n\n")
    cat(text$comp, "\n\n")
    cat(text$avail, "\n\n")
    cat(text$universe, "\n\n")
    cat("#### Results {.unnumbered} \n\n")
    if(is.null(text$tbl)){
      cat("*Table omitted for space constraints*\n\n")
    } else {
      text$tbl %>% as_raw_html() %>% cat()
    }
  })

```

