---
title: "New Online Course: Introduction to IPUMS PMA Data Analysis"
description: |
  Explore IPUMS PMA data with R right in your browser, or download Stata code for offline practice
date: 08-07-2021
output:
  distill::distill_article:
    self_contained: false
preview: ../../images/new_course.png
---

Today, we're proud to announce the launch of a brand new feature on the IPUMS PMA Data Analysis Hub: our very first online course! 

Whether you're a beginner-level data analyst exploring statistical software for the first time, or if you're a more advanced analyst looking for a guided tour of IPUMS PMA data, we think our new [Introduction to IPUMS PMA Data Analysis](../../introduction.html) is a great place to start. Over time, we'll add courses on more advanced topics in the new **Courses** menu in the navigation bar at the top of your screen.

<aside>
```{r, echo=F}
htmltools::a(
  href = "../../introduction.html",
  htmltools::img(src = "../../images/new_course.png")
)
```
[Click here](../../introduction.html) to get started
</aside>

We expect most people will probably need **about an hour** to complete the Introduction course, but you're welcome to work at your own pace. You can also leave and resume your progress at any time. 

Upon completion, we offer a **downloadable certificate** signed by the IPUMS PMA team, plus a script containing all of the code you mastered during the course. 

# Requirements 

IPUMS PMA data are **free** to use, and all of our online courses will be free, as well. To get started, you just need to [register](https://pma.ipums.org/pma/register.shtml) and agree to our Terms of Use. 

We've created exercises for **both R and Stata users**, so you'll need to choose a preferred language at the start of each course. 

  * R users: you'll find an embedded R console where you can practice coding exercises **right in your browser**. We've pre-installed all of the packages necessary to complete each exercise, and you'll receive **interactive feedback** to help you identify any mistakes along the way. 
  * Stata users: you'll need access to a copy of the Stata program. We'll provide example code that you'll run **offline**, and you'll need to use the output from Stata to answer multiple choice questions in our "guided practice" section. 
  
<aside>
We're able to offer interactive practice and feedback to R users thanks to the amazing [learnr](https://rstudio.github.io/learnr/) and [gradethis](https://github.com/rstudio/gradethis) packages for R. 
</aside>

IPUMS PMA courses are hosted by [Qualtrics](https://www.qualtrics.com/), so you **may need to deactive your browser's ad blocker** in order see course content. If you have any difficulties, please [contact us](mailto:ipumsgh@umn.edu)! 